require 'eth'
require 'ethereum.rb'
require 'jwt'
require 'logger'
require 'pry'
require 'virtus_convert'
require 'virtus'
require 'silkey'

require_relative 'silkey/contract'
require_relative 'silkey/configuration'
require_relative 'silkey/factories/client_factory'
require_relative 'silkey/factories/contract_factory'
require_relative 'silkey/models/jwt_payload'
require_relative 'silkey/models/settings'
require_relative 'silkey/models/sso_params'
require_relative 'silkey/services/logger_service'
require_relative 'silkey/services/verifier'
require_relative 'silkey/sdk'
require_relative 'silkey/utils'

require_relative 'silkey/registry_contract/registry_contract'
